@echo off
REM xMobu Installation Script
REM Automatically configures MotionBuilder to load xMobu on startup

echo.
echo ========================================
echo  xMobu Installation
echo ========================================
echo.

REM Get the directory where this script is located
set "XMOBU_ROOT=%~dp0"
set "XMOBU_ROOT=%XMOBU_ROOT:~0,-1%"

echo xMobu Root: %XMOBU_ROOT%
echo.

REM Detect MotionBuilder installations
echo Detecting MotionBuilder installations...
echo.

set "MOBU_FOUND=0"
set "MOBU_VERSIONS="

REM Check common installation paths for MotionBuilder 2020-2025
for %%v in (2025 2024 2023 2022 2021 2020) do (
    if exist "C:\Program Files\Autodesk\MotionBuilder %%v" (
        echo [*] Found MotionBuilder %%v
        set "MOBU_FOUND=1"
        set "MOBU_VERSIONS=!MOBU_VERSIONS! %%v"
    )
)

if "%MOBU_FOUND%"=="0" (
    echo.
    echo [!] No MotionBuilder installation detected in default location
    echo     If MotionBuilder is installed elsewhere, you'll need to manually configure it.
    echo.
    echo Manual Installation:
    echo 1. Locate your MotionBuilder installation folder
    echo 2. Navigate to: config\PythonStartup
    echo 3. Create/Edit a .py file to add:
    echo    import sys
    echo    sys.path.insert(0, '%XMOBU_ROOT%')
    echo    import mobu.startup
    echo.
    pause
    exit /b 1
)

echo.
echo Found MotionBuilder installations. Choose a version to configure:
echo.

REM List available versions
set /a count=0
for %%v in (%MOBU_VERSIONS%) do (
    set /a count+=1
    echo [!count!] MotionBuilder %%v
    set "VERSION_!count!=%%v"
)

echo [A] Install for ALL detected versions
echo [Q] Quit
echo.

set /p "choice=Enter your choice: "

if /i "%choice%"=="Q" (
    echo Installation cancelled.
    exit /b 0
)

if /i "%choice%"=="A" (
    echo.
    echo Installing for ALL MotionBuilder versions...
    for %%v in (%MOBU_VERSIONS%) do (
        call :InstallForVersion %%v
    )
    goto :Done
)

REM Install for specific version
if defined VERSION_%choice% (
    call set "SELECTED_VERSION=%%VERSION_%choice%%%"
    echo.
    echo Installing for MotionBuilder !SELECTED_VERSION!...
    call :InstallForVersion !SELECTED_VERSION!
    goto :Done
) else (
    echo Invalid choice!
    pause
    exit /b 1
)

:InstallForVersion
set "VERSION=%~1"
set "MOBU_PATH=C:\Program Files\Autodesk\MotionBuilder %VERSION%"
set "STARTUP_PATH=%MOBU_PATH%\bin\config\PythonStartup"

echo.
echo Configuring MotionBuilder %VERSION%...
echo Startup path: %STARTUP_PATH%

REM Create PythonStartup directory if it doesn't exist
if not exist "%STARTUP_PATH%" (
    echo Creating PythonStartup directory...
    mkdir "%STARTUP_PATH%"
)

REM Create the startup script
set "STARTUP_FILE=%STARTUP_PATH%\xmobu_init.py"

echo Creating startup script: %STARTUP_FILE%

(
echo # xMobu Startup Script
echo # Auto-generated by xMobu installer
echo # This file is executed when MotionBuilder starts
echo.
echo import sys
echo from pathlib import Path
echo.
echo # Add xMobu to Python path
echo xmobu_root = r'%XMOBU_ROOT%'
echo if xmobu_root not in sys.path:
echo     sys.path.insert(0, xmobu_root^)
echo     print(f"xMobu: Added {xmobu_root} to Python path"^)
echo.
echo # Initialize xMobu
echo try:
echo     import mobu.startup
echo     print("xMobu: Initialized successfully"^)
echo except Exception as e:
echo     print(f"xMobu: Initialization failed - {str(e^)}"^)
echo     import traceback
echo     traceback.print_exc(^)
) > "%STARTUP_FILE%"

if exist "%STARTUP_FILE%" (
    echo [OK] MotionBuilder %VERSION% configured successfully!
) else (
    echo [ERROR] Failed to create startup script for MotionBuilder %VERSION%
)

goto :eof

:Done
echo.
echo ========================================
echo  Installation Complete!
echo ========================================
echo.
echo xMobu has been installed successfully!
echo.
echo Next steps:
echo 1. Start MotionBuilder
echo 2. Look for the "xMobu" menu in the menu bar
echo 3. Explore the available tools in the submenus
echo.
echo Configuration:
echo - Edit config/config.json to customize settings
echo - Add custom tools to mobu/tools/ folders
echo - Check README.md for more information
echo.
echo To uninstall:
echo - Run uninstall.bat
echo - Or manually delete xmobu_init.py from: MotionBuilder\bin\config\PythonStartup\
echo.
pause
