# MotionKit Startup Script
# Auto-generated by MotionKit installer
# This file is executed when MotionBuilder starts

import sys
from pathlib import Path

# Add MotionKit to Python path
motionkit_root = r'C:\Users\elementa\projects\MotionKit'
if motionkit_root not in sys.path:
    sys.path.insert(0, motionkit_root)
    print(f"[MotionKit] Added {motionkit_root} to Python path")
else:
    print(f"[MotionKit] {motionkit_root} already in Python path")

# Initialize MotionKit
print("[MotionKit] Initializing MotionKit menu system...")
try:
    import mobu.startup
    print("[MotionKit] Initialization completed successfully!")
    print("[MotionKit] Menu should appear in: MotionKit > [categories]")
except ImportError as e:
    print(f"[MotionKit ERROR] Import failed - {str(e)}")
    print("[MotionKit ERROR] Check that all MotionKit files are present")
    import traceback
    traceback.print_exc()
except Exception as e:
    print(f"[MotionKit ERROR] Initialization failed - {str(e)}")
    import traceback
    traceback.print_exc()
