# xMobu Startup Script
# Auto-generated by xMobu installer
# This file is executed when MotionBuilder starts

import sys
from pathlib import Path

# Add xMobu to Python path
xmobu_root = r'C:\Users\elementa\projects\xMobu'
if xmobu_root not in sys.path:
    sys.path.insert(0, xmobu_root)
    print(f"[xMobu] Added {xmobu_root} to Python path")
else:
    print(f"[xMobu] {xmobu_root} already in Python path")

# Initialize xMobu
print("[xMobu] Initializing xMobu menu system...")
try:
    import mobu.startup
    print("[xMobu] Initialization completed successfully!")
    print("[xMobu] Menu should appear in: xMobu > [categories]")
except ImportError as e:
    print(f"[xMobu ERROR] Import failed - {str(e)}")
    print("[xMobu ERROR] Check that all xMobu files are present")
    import traceback
    traceback.print_exc()
except Exception as e:
    print(f"[xMobu ERROR] Initialization failed - {str(e)}")
    import traceback
    traceback.print_exc()
